/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.ServerController;
import java.io.File;
import javax.swing.JOptionPane;
import networkElements.Address;
import networkElements.ConnectionUDP;
import networkElements.IpProtocol;
import server.Server;
import utils.FileChooser;

/**
 *
 * @author João Fernandes - 1141114 José Barros - 1151117 José Rodrigues - 1150710 Tiago Vilaça - 1140412
 */
public class ServerMenuUI extends javax.swing.JFrame {

    private final ServerController serverController;

    /**
     * Creates new form ServerMenuUI
     *
     * @param server
     */
    public ServerMenuUI(Server server) {

        serverController = new ServerController(server);
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextServerIp = new javax.swing.JTextField();
        jTextServerBroadcastIp = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabelServerStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextIpAddress = new javax.swing.JTextField();
        refreshJButton = new javax.swing.JButton();
        sendToAllJButton = new javax.swing.JButton();
        jTextTotalSizeOfFiles = new javax.swing.JTextField();
        jTextNumberOfFiles = new javax.swing.JTextField();
        jButtonOnOffServerBroadcast = new javax.swing.JButton();
        jButtonChooseDirectory = new javax.swing.JButton();
        jTextFilePath = new javax.swing.JTextField();
        jTextUpdateRate = new javax.swing.JTextField();
        jButtonSeeLog = new javax.swing.JButton();
        jButtonSettings = new javax.swing.JButton();
        jProgressBarSending = new javax.swing.JProgressBar();
        jButtonRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 36)); // NOI18N
        jLabel1.setText("Server");

        jTextServerIp.setEditable(false);
        jTextServerIp.setText(serverController.getServerAddress().getAddress());
        jTextServerIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextServerIpActionPerformed(evt);
            }
        });

        jTextServerBroadcastIp.setEditable(false);
        jTextServerBroadcastIp.setText(serverController.getServerAddress().getBroadcastAddress());
        jTextServerBroadcastIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextServerBroadcastIpActionPerformed(evt);
            }
        });

        jLabel2.setText("IP");

        jLabel3.setText("Broadcast");

        jlabelServerStatus.setText((serverController.isServerStatusActive()) ? "Server On":"Server Off");

        jLabel5.setText("File List:");

        jList1.setModel(utils.Utils.returnModelForJList(serverController.listAllFiles()));
        jList1.setToolTipText(" ");
        jScrollPane1.setViewportView(jList1);

        jLabel6.setText("Number Files:");

        jLabel7.setText("Size of Files:");

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("List broadcast update rate (seconds)");

        jLabel9.setText("Broadcast: " + serverController.getServerAddress().getBroadcastAddress());

        jTextIpAddress.setText("\"e0:db:55:dd:7f:4c\" or \"192.168.0.1\"");

        refreshJButton.setText("Send");
        refreshJButton.setActionCommand("refresh");
        refreshJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshJButtonActionPerformed(evt);
            }
        });

        sendToAllJButton.setText("Send to all (broadcast)");
        sendToAllJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendToAllJButtonActionPerformed(evt);
            }
        });

        jTextTotalSizeOfFiles.setEditable(false);
        jTextTotalSizeOfFiles.setText("" + utils.Utils.totalSizeOfFiles(serverController.listAllFiles()));

        jTextNumberOfFiles.setEditable(false);
        jTextNumberOfFiles.setText(""+serverController.amountOfFiles());

        jButtonOnOffServerBroadcast.setText("On/Off File Update Signal");
        jButtonOnOffServerBroadcast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOnOffServerBroadcastActionPerformed(evt);
            }
        });

        jButtonChooseDirectory.setText("Choose directory");
        jButtonChooseDirectory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChooseDirectoryActionPerformed(evt);
            }
        });

        jTextFilePath.setEditable(false);
        jTextFilePath.setText("File Path (default path)");

        jTextUpdateRate.setText(""+serverController.getSecondsToSendUDP());

        jButtonSeeLog.setText("Show Access Log");
        jButtonSeeLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeLogActionPerformed(evt);
            }
        });

        jButtonSettings.setText("Settings");
        jButtonSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSettingsActionPerformed(evt);
            }
        });

        jButtonRefresh.setText("Refresh");
        jButtonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonChooseDirectory, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(33, 33, 33)
                                .addComponent(jButtonRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonSeeLog, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonOnOffServerBroadcast)
                                .addGap(28, 28, 28)
                                .addComponent(jlabelServerStatus)
                                .addGap(30, 30, 30)
                                .addComponent(jProgressBarSending, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sendToAllJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                                .addGap(28, 28, 28)
                                                .addComponent(jTextNumberOfFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel7)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(124, 124, 124)
                                        .addComponent(jTextServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                .addGap(28, 28, 28)
                                                .addComponent(jTextServerBroadcastIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jTextTotalSizeOfFiles, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jTextUpdateRate, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(refreshJButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonRefresh))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextServerBroadcastIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextServerIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(14, 14, 14)))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNumberOfFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jTextTotalSizeOfFiles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextUpdateRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendToAllJButton)
                            .addComponent(jLabel9))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextIpAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(refreshJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 57, 57)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonChooseDirectory)
                    .addComponent(jButtonOnOffServerBroadcast)
                    .addComponent(jlabelServerStatus)
                    .addComponent(jProgressBarSending, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonSeeLog)
                        .addComponent(jButtonSettings)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextServerIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextServerIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextServerIpActionPerformed

    private void jTextServerBroadcastIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextServerBroadcastIpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextServerBroadcastIpActionPerformed

    private void refreshJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshJButtonActionPerformed
        // TODO add your handling code here:
        String ip = jTextIpAddress.getText();
        if (utils.Utils.validateAddress(ip, "ipv4")) {
            serverController.setAddressToSendUdp(new Address(IpProtocol.IPV4, ip,
                    serverController.getServerAddress().getMaskAddress(),
                    serverController.getServerAddress().getBroadcastAddress(), ABORT, ABORT));
        }


    }//GEN-LAST:event_refreshJButtonActionPerformed

    private void sendToAllJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendToAllJButtonActionPerformed
        // TODO add your handling code here:
        Address a = new Address(IpProtocol.IPV4,
                serverController.getServerAddress().getBroadcastAddress(),
                "not necessarie", serverController.getServerAddress().getBroadcastAddress(),
                ConnectionUDP.PORT_UDP_FOR_SERVER_UPLOAD_DEFAULT, -1);
        serverController.setAddressToSendUdp(a);
        jTextIpAddress.setText("" + a.getAddress());
    }//GEN-LAST:event_sendToAllJButtonActionPerformed

    private void jButtonChooseDirectoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChooseDirectoryActionPerformed
        FileChooser fileChooser = new FileChooser();
        try {
            String filePath = fileChooser.openFileChooser();
            if (filePath != null || !filePath.isEmpty() || filePath.equalsIgnoreCase("null")) {
                jTextFilePath.setText(filePath);
                serverController.setFolderToSharePath(new File(filePath));
                jTextFilePath.setText(filePath);
                jList1.setModel(utils.Utils.returnModelForJList(serverController.listAllFiles()));
            }
        } catch (NullPointerException e) {
            File f = new File(Server.FOLDER_PATH_TO_SHARE_DEFAULT);
            serverController.setFolderToSharePath(f);
            jTextFilePath.setText(f.getPath());
            jList1.setModel(utils.Utils.returnModelForJList(serverController.listAllFiles()));
        }

    }//GEN-LAST:event_jButtonChooseDirectoryActionPerformed

    private void jButtonOnOffServerBroadcastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOnOffServerBroadcastActionPerformed
        String textToJLabel;
        /**
         * server alreasy on --> turnOff
         */
        if (serverController.isServerStatusActive()) {
            serverController.turnOffServer();
            jProgressBarSending.setIndeterminate(false);
            textToJLabel = "Server Off";
        } else {
            if (serverController.getAddressToSendUdp().getAddress().equalsIgnoreCase("empty")) {
                JOptionPane.showMessageDialog(this,
                        "The client/node ip to send is empty, please alter it..",
                        "Network Error",
                        JOptionPane.ERROR_MESSAGE);
                textToJLabel = "Server Off";
            } else {
                /**
                 * Server off, turn on
                 */
                serverController.turnOnServer();
                textToJLabel = "Server On";
                jProgressBarSending.setIndeterminate(true);
            }

        }
        jlabelServerStatus.setText(textToJLabel);
    }//GEN-LAST:event_jButtonOnOffServerBroadcastActionPerformed

    private void jButtonSeeLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeLogActionPerformed
        // TODO add your handling code here:
        new LogFileShowUI(serverController.getClientLogList());
    }//GEN-LAST:event_jButtonSeeLogActionPerformed

    private void jButtonSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSettingsActionPerformed
        // TODO add your handling code here:
        new SettingsUI();
    }//GEN-LAST:event_jButtonSettingsActionPerformed

    private void jButtonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRefreshActionPerformed
        // TODO add your handling code here:
        jList1.setModel(utils.Utils.returnModelForJList(serverController.listAllFiles()));
        jTextTotalSizeOfFiles.setText( utils.Utils.totalSizeOfFiles(serverController.listAllFiles()));
    }//GEN-LAST:event_jButtonRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChooseDirectory;
    private javax.swing.JButton jButtonOnOffServerBroadcast;
    private javax.swing.JButton jButtonRefresh;
    private javax.swing.JButton jButtonSeeLog;
    private javax.swing.JButton jButtonSettings;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JProgressBar jProgressBarSending;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFilePath;
    private javax.swing.JTextField jTextIpAddress;
    private javax.swing.JTextField jTextNumberOfFiles;
    private javax.swing.JTextField jTextServerBroadcastIp;
    private javax.swing.JTextField jTextServerIp;
    private javax.swing.JTextField jTextTotalSizeOfFiles;
    private javax.swing.JTextField jTextUpdateRate;
    private javax.swing.JLabel jlabelServerStatus;
    private javax.swing.JButton refreshJButton;
    private javax.swing.JButton sendToAllJButton;
    // End of variables declaration//GEN-END:variables
}
